title: "邻禾里"
description: "邻禾里,生活是一手好菜"
baseurl: ""
url: ""

markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

collections:
  pages:
    output: true

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
